//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VK {
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public partial class VKApiManager {
        
        public class Subscriptions : VKAPIBranch {
            
            private const string API_BRANCH = "subscriptions.{0}";
            
            /// <summary>Создает объект класса <typeparamref name="Subscriptions"/>.</summary>
            public Subscriptions(bool needXml) : 
                    base(needXml) {
                API_URI_BASE_TEMPLATE = String.Format(API_URI_BASE, API_BRANCH);
            }
            
            #region subscriptions.get
            /// <summary>Возвращает список идентификаторов пользователей, которые входят в список подписок текущего пользователя. Идентификаторы пользователей в списке отсортированы в порядке убывания времени их добавления.</summary>
            /// <param name="uid">идентификатор пользователя, список которого необходимо получить</param>
            /// <param name="offset">смещение относительно начала списка, для выборки определенного подмножества</param>
            /// <param name="count">количество возвращаемых идентификаторов пользователей</param>
            /// <returns>Ответ сервера в XML или JSON формате.</returns>
            private VKResponseBase get(System.Int64? uid, System.Int32? offset, System.Int32? count) {
                manager.AddValueByName("@uid", uid);
                manager.AddValueByName("@offset", offset);
                manager.AddValueByName("@count", count);
                return new VKResponseBase(GetResponse("get"), IsXMLResponse);
            }
            
            /// <summary>Возвращает список идентификаторов пользователей, которые входят в список подписок текущего пользователя. Идентификаторы пользователей в списке отсортированы в порядке убывания времени их добавления.</summary>
            /// <param name="uid">идентификатор пользователя, список которого необходимо получить</param>
            /// <param name="offset">смещение относительно начала списка, для выборки определенного подмножества</param>
            /// <param name="count">количество возвращаемых идентификаторов пользователей</param>
            /// <returns>Ответ сервера в XML или JSON формате.</returns>
            public VKResponseBase Get(System.Int64? uid = null, System.Int32? offset = null, System.Int32? count = null) {
                return get(uid, offset, count);
            }
            #endregion
            
            #region subscriptions.getFollowers
            /// <summary>Возвращает список идентификаторов пользователей, которые являются подписчиками текущего пользователя. Идентификаторы пользователей в списке отсортированы в порядке убывания времени их добавления.</summary>
            /// <param name="uid">идентификатор пользователя, список которого необходимо получить</param>
            /// <param name="offset">смещение, относительно начала списка, для выборки определенного подмножества</param>
            /// <param name="count">количество возвращаемых идентификаторов пользователей</param>
            /// <returns>Ответ сервера в XML или JSON формате.</returns>
            private VKResponseBase getFollowers(System.Int64? uid, System.Int32? offset, System.Int32? count) {
                manager.AddValueByName("@uid", uid);
                manager.AddValueByName("@offset", offset);
                manager.AddValueByName("@count", count);
                return new VKResponseBase(GetResponse("getFollowers"), IsXMLResponse);
            }
            
            /// <summary>Возвращает список идентификаторов пользователей, которые являются подписчиками текущего пользователя. Идентификаторы пользователей в списке отсортированы в порядке убывания времени их добавления.</summary>
            /// <param name="uid">идентификатор пользователя, список которого необходимо получить</param>
            /// <param name="offset">смещение, относительно начала списка, для выборки определенного подмножества</param>
            /// <param name="count">количество возвращаемых идентификаторов пользователей</param>
            /// <returns>Ответ сервера в XML или JSON формате.</returns>
            public VKResponseBase GetFollowers(System.Int64? uid = null, System.Int32? offset = null, System.Int32? count = null) {
                return getFollowers(uid, offset, count);
            }
            #endregion
            
            #region subscriptions.follow
            /// <summary>Добавляет указанного пользователя в список подписок текущего пользователя.</summary>
            /// <param name="uid">идентификатор пользователя, которого необходимо добавить в список подписок</param>
            /// <returns>Ответ сервера в XML или JSON формате.</returns>
            private VKResponseBase follow(System.Int64? uid) {
                manager.AddValueByName("@uid", uid);
                return new VKResponseBase(GetResponse("follow"), IsXMLResponse);
            }
            
            /// <summary>Добавляет указанного пользователя в список подписок текущего пользователя.</summary>
            /// <param name="uid">идентификатор пользователя, которого необходимо добавить в список подписок</param>
            /// <returns>Ответ сервера в XML или JSON формате.</returns>
            public VKResponseBase Follow(System.Int64? uid) {
                return follow(uid);
            }
            #endregion
            
            #region subscriptions.unfollow
            /// <summary>Удаляет указанного пользователя из списка подписок текущего пользователя.</summary>
            /// <param name="uid">идентификатор пользователя, которого необходимо удалить из списка подписок</param>
            /// <returns>Ответ сервера в XML или JSON формате.</returns>
            private VKResponseBase unfollow(System.Int64? uid) {
                manager.AddValueByName("@uid", uid);
                return new VKResponseBase(GetResponse("unfollow"), IsXMLResponse);
            }
            
            /// <summary>Удаляет указанного пользователя из списка подписок текущего пользователя.</summary>
            /// <param name="uid">идентификатор пользователя, которого необходимо удалить из списка подписок</param>
            /// <returns>Ответ сервера в XML или JSON формате.</returns>
            public VKResponseBase Unfollow(System.Int64? uid) {
                return unfollow(uid);
            }
            #endregion
        }
    }
}
