//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VK {
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public partial class VKApiManager {
        
        public class Status : VKAPIBranch {
            
            private const string API_BRANCH = "status.{0}";
            
            /// <summary>Создает объект класса <typeparamref name="Status"/>.</summary>
            public Status(bool needXml) : 
                    base(needXml) {
                API_URI_BASE_TEMPLATE = String.Format(API_URI_BASE, API_BRANCH);
            }
            
            #region status.get
            /// <summary></summary>
            /// <param name="uid">идентификатор пользователя, статус которого необходимо получить</param>
            /// <returns>Ответ сервера в XML или JSON формате.</returns>
            private VKResponseBase get(System.Int64? uid) {
                manager.AddValueByName("@uid", uid);
                return new VKResponseBase(GetResponse("get"), IsXMLResponse);
            }
            
            /// <summary></summary>
            /// <param name="uid">идентификатор пользователя, статус которого необходимо получить</param>
            /// <returns>Ответ сервера в XML или JSON формате.</returns>
            public VKResponseBase Get(System.Int64? uid) {
                return get(uid);
            }
            #endregion
            
            #region status.set
            /// <summary>Устанавливает новый статус текущему пользователю.</summary>
            /// <param name="text">текст статуса, который необходимо установить текущему пользователю</param>
            /// <param name="audio">текущая аудиозапись, которую необходимо транслировать в статус, задается в формате oid_aid (идентификатор владельца и идентификатор аудиозаписи, разделенные знаком подчеркивания)</param>
            /// <returns>Ответ сервера в XML или JSON формате.</returns>
			private VKResponseBase set(string text, Id audio) {
                manager.AddValueByName("@text", text);
                manager.AddValueByName("@audio", audio);
                return new VKResponseBase(GetResponse("set"), IsXMLResponse);
            }
            
            /// <summary>Устанавливает новый статус текущему пользователю.</summary>
            /// <param name="text">текст статуса, который необходимо установить текущему пользователю</param>
            /// <returns>Ответ сервера в XML или JSON формате.</returns>
            public VKResponseBase Set(string text) {
                return set(text, null);
            }
            
            /// <summary>Устанавливает новый статус текущему пользователю.</summary>
            /// <param name="audio">текущая аудиозапись, которую необходимо транслировать в статус, задается в формате oid_aid (идентификатор владельца и идентификатор аудиозаписи, разделенные знаком подчеркивания)</param>
            /// <returns>Ответ сервера в XML или JSON формате.</returns>
            public VKResponseBase Set(Id audio) {
                return set(null, audio);
            }
            #endregion
        }
    }
}
