//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VK {
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public partial class VKApiManager {
        
        public class Polls : VKAPIBranch {
            
            private const string API_BRANCH = "polls.{0}";
            
            /// <summary>Создает объект класса <typeparamref name="Polls"/>.</summary>
            public Polls(bool needXml) : 
                    base(needXml) {
                API_URI_BASE_TEMPLATE = String.Format(API_URI_BASE, API_BRANCH);
            }
            
            #region polls.getById
            /// <summary>Возвращает детальную информацию об опросе по его идентификатору.</summary>
            /// <param name="owner_id">идентификатор владельца опроса, информацию о котором необходимо получить</param>
            /// <param name="poll_id">идентификатор опроса, информацию о котором необходимо получить</param>
            /// <returns>Ответ сервера в XML или JSON формате.</returns>
            private VKResponseBase getById(System.Int64? owner_id, System.Int64? poll_id) {
                manager.AddValueByName("@owner_id", owner_id);
                manager.AddValueByName("@poll_id", poll_id);
                return new VKResponseBase(GetResponse("getById"), IsXMLResponse);
            }
            
            /// <summary>Возвращает детальную информацию об опросе по его идентификатору.</summary>
            /// <param name="owner_id">идентификатор владельца опроса, информацию о котором необходимо получить</param>
            /// <param name="poll_id">идентификатор опроса, информацию о котором необходимо получить</param>
            /// <returns>Ответ сервера в XML или JSON формате.</returns>
            public VKResponseBase GetById(System.Int64? owner_id, System.Int64? poll_id) {
                return getById(owner_id, poll_id);
            }
            #endregion
            
            #region polls.addVote
            /// <summary>Отдает голос текущего пользователя за выбранный вариант ответа в указанном опросе.</summary>
            /// <param name="owner_id">идентификатор владельца опроса</param>
            /// <param name="poll_id">идентификатор опроса, в котором необходимо проголосовать</param>
            /// <param name="answer_id">идентификатор варианта ответа, за который необходимо проголосовать</param>
            /// <returns>Ответ сервера в XML или JSON формате.</returns>
			private VKResponseBase addVote(System.Int64? owner_id, System.Int64? poll_id, System.Int64? answer_id) {
                manager.AddValueByName("@owner_id", owner_id);
                manager.AddValueByName("@poll_id", poll_id);
                manager.AddValueByName("@answer_id", answer_id);
                return new VKResponseBase(GetResponse("addVote"), IsXMLResponse);
            }
            
            /// <summary>Отдает голос текущего пользователя за выбранный вариант ответа в указанном опросе.</summary>
            /// <param name="owner_id">идентификатор владельца опроса</param>
            /// <param name="poll_id">идентификатор опроса, в котором необходимо проголосовать</param>
            /// <param name="answer_id">идентификатор варианта ответа, за который необходимо проголосовать</param>
            /// <returns>Ответ сервера в XML или JSON формате.</returns>
            public VKResponseBase AddVote(System.Int64? owner_id, System.Int64? poll_id, System.Int64? answer_id) {
                return addVote(owner_id, poll_id, answer_id);
            }
            #endregion
            
            #region polls.deleteVote
            /// <summary>Снимает голос текущего пользователя с выбранного варианта ответа в указанном опросе.</summary>
            /// <param name="owner_id">идентификатор владельца опроса</param>
            /// <param name="poll_id">идентификатор опроса, в котором необходимо снять голос</param>
            /// <param name="answer_id">идентификатор варианта ответа, с которого необходимо снять голос</param>
            /// <returns>Ответ сервера в XML или JSON формате.</returns>
			private VKResponseBase deleteVote(System.Int64? owner_id, System.Int64? poll_id, System.Int64? answer_id) {
                manager.AddValueByName("@owner_id", owner_id);
                manager.AddValueByName("@poll_id", poll_id);
                manager.AddValueByName("@answer_id", answer_id);
                return new VKResponseBase(GetResponse("deleteVote"), IsXMLResponse);
            }
            
            /// <summary>Снимает голос текущего пользователя с выбранного варианта ответа в указанном опросе.</summary>
            /// <param name="owner_id">идентификатор владельца опроса</param>
            /// <param name="poll_id">идентификатор опроса, в котором необходимо снять голос</param>
            /// <param name="answer_id">идентификатор варианта ответа, с которого необходимо снять голос</param>
            /// <returns>Ответ сервера в XML или JSON формате.</returns>
            public VKResponseBase DeleteVote(System.Int64? owner_id, System.Int64? poll_id, System.Int64? answer_id) {
                return deleteVote(owner_id, poll_id, answer_id);
            }
            #endregion
        }
    }
}
