//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VK {
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public partial class VKApiManager {
        
        public class SMS : VKAPIBranch {
            
            private const string API_BRANCH = "sms.{0}";
            
            /// <summary>Создает объект класса <typeparamref name="SMS"/>.</summary>
            public SMS(bool needXml) : 
                    base(needXml) {
                API_URI_BASE_TEMPLATE = String.Format(API_URI_BASE, API_BRANCH);
            }
            
            #region setSMSPrefix
            /// <summary>Устанавливает префикс для обеспечения уникальности приложения-получателя</summary>
            /// <param name="prefix">3-16 символов латинского алфавита в формате UTF-8</param>
            /// <returns>Ответ сервера в XML или JSON формате.</returns>
            private VKResponseBase setSMSPrefix(string prefix) {
                manager.AddValueByName("@prefix", prefix);
                return new VKResponseBase(GetResponse("setSMSPrefix", true), IsXMLResponse);
            }
            
            /// <summary>Устанавливает префикс для обеспечения уникальности приложения-получателя</summary>
            /// <param name="prefix">3-16 символов латинского алфавита в формате UTF-8</param>
            /// <returns>Ответ сервера в XML или JSON формате.</returns>
            public VKResponseBase SetSMSPrefix(string prefix) {
                return setSMSPrefix(prefix);
            }
            #endregion
            
            #region getSMSPrefix
            /// <summary>Возвращает префикс</summary>
            /// <returns>Ответ сервера в XML или JSON формате.</returns>
            private VKResponseBase getSMSPrefix() {
                return new VKResponseBase(GetResponse("getSMSPrefix", true), IsXMLResponse);
            }
            
            /// <summary>Возвращает префикс</summary>
            /// <returns>Ответ сервера в XML или JSON формате.</returns>
            public VKResponseBase GetSMSPrefix() {
                return getSMSPrefix();
            }
            #endregion
        }
    }
}
